version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=users_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    driver: local