name: login-registration-springboot-hibernate-jsp-auth

on:
  push:
    paths:
      - "login-registration-springboot-hibernate-jsp-auth/**"
    branches: [master]
  pull_request:
    paths:
      - "login-registration-springboot-hibernate-jsp-auth/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: login-registration-springboot-hibernate-jsp-auth
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 17
          distribution: "adopt"
          cache: "maven"
      - name: Build and analyze
        run: mvn clean package