name: springboot2-webapp-thymeleaf

on:
  push:
    paths:
      - "springboot2-webapp-thymeleaf/**"
    branches: [master]
  pull_request:
    paths:
      - "springboot2-webapp-thymeleaf/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 8
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 8
          distribution: "adopt"
          cache: "maven"
      - name: Build and analyze
        run: |
          cd springboot2-webapp-thymeleaf
          chmod +x mvnw
          ./mvnw clean package