name: springboot2-externalizing-conf-properties

on:
  push:
    paths:
      - "springboot2-externalizing-conf-properties/**"
    branches: [master]
  pull_request:
    paths:
      - "springboot2-externalizing-conf-properties/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: "adopt"
          cache: "maven"
      - name: Build and analyze
        run: |
          cd springboot2-externalizing-conf-properties
          mvn clean package